services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: DentalClinicDB
      MYSQL_ROOT_PASSWORD: 2003@Nethindu
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dental-network

  discovery-server:
    build:
      context: ./discovery_server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - dental-network

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      - discovery-server
    networks:
      - dental-network

  identity-service:
    build:
      context: ./identity_service
      dockerfile: Dockerfile
    container_name: identity-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/DentalClinicDB?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "2003@Nethindu"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - dental-network

  chat-service:
    build:
      context: ./chat_service
      dockerfile: Dockerfile
    container_name: chat-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/DentalClinicDB?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "2003@Nethindu"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    depends_on:
      mysql:
        condition: service_healthy
      discovery-server:
        condition: service_started
    networks:
      - dental-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dental-client
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - dental-network

networks:
  dental-network:
    driver: bridge

volumes:
  mysql_data:
