server:
  port: 8081 # Important: Identity runs on 8081

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:mysql://localhost:3306/DentalClinicDB
    username: root
    password: 2003@Nethindu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nethindu359@gmail.com
    password: ouyk cawa bufg izcz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/